info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
foo: baz
apic: chr

spring
  profiles
    active:GetaLoan
    
GetaLoan
  Errors[0]
    code:401
    message:Unauthorized
    level:Error
    description:The authorization is not valid.
